osx_image: xcode61
language: objective-c
before_install: gem install cocoapods xcpretty -N
cache: cocoapods
podfile: JazzHandsDemo/Podfile
script:
    - export LC_CTYPE=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - set -o pipefail && xcodebuild -workspace JazzHandsDemo/JazzHandsDemo.xcworkspace -scheme JazzHandsDemo -sdk iphonesimulator clean analyze ONLY_ACTIVE_ARCH=NO | xcpretty -c
